heat_template_version: 2013-05-23

description: Deploy An edX (Birch) Environment

parameters:
  domain:
    type: string
    label: Domain
    default: cloudtrain.me

resources:
  password:
    type: OS::Heat::RandomString
    properties:
      length: 12
      sequence: lettersdigits

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: "%prefix%-edx-keypair"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      save_private_key: True

  network:
    type: Rackspace::Cloud::Network
    properties:
      cidr: 192.168.2.0/24
      label:
        str_replace:
          template: "%prefix%-edx-private"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }

  database:
    type: OS::Trove::Instance
    properties:
      name:
        str_replace:
          template: "%prefix%-edx-database"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      flavor: 1GB Instance
      size: 5
      networks:
        - network: 00000000-0000-0000-0000-000000000000
        - network: 11111111-1111-1111-1111-111111111111
        - network: { get_resource: network }
      datastore_type: "mysql"
      datastore_version: "5.6"
      databases:
        - name: edxapp
        - name: xqueue
        - name: ora
      users:
        - name: admin
          password: { get_attr: [ password, value ] }
          databases:
            - edxapp
            - xqueue
            - ora
        - name: read_only
          password: { get_attr: [ password, value ] }
          databases:
            - edxapp
            - xqueue
            - ora
        - name: migrate
          password: { get_attr: [ password, value ] }
          databases:
            - edxapp
            - xqueue
            - ora
        - name: edxapp001
          password: { get_attr: [ password, value ] }
          databases:
            - edxapp
        - name: xqueue001
          password: { get_attr: [ password, value ] }
          databases:
            - xqueue
        - name: ora001
          password: { get_attr: [ password, value ] }
          databases:
            - ora

  swift_signal_handle_app1:
    type: OS::Heat::SwiftSignalHandle

  cloud_config_app1:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        output:
          all: '| tee -a /var/log/cloud-init-output.log'
        apt_upgrade: true
        packages:
          - tmux
          - htop
          - multitail
          - build-essential
          - software-properties-common
          - python-software-properties
          - curl
          - git-core
          - libxml2-dev
          - libxslt1-dev
          - libfreetype6-dev
          - python-pip
          - python-apt
          - python-dev
        runcmd:
          - mkdir -p /opt/cloud-training
          - str_replace:
              template: |
                cat > /opt/cloud-training/ansible-environment.yml << EOF
                ---
                edx_platform_version: 'named-release/birch'
                ora2_version: 'named-release/birch'
                certs_version: 'named-release/birch'
                forum_version: 'named-release/birch'
                xqueue_version: 'named-release/birch'
                
                EDXAPP_PREVIEW_LMS_BASE: 'preview.edx.%prefix%.%domain%'
                EDXAPP_LMS_BASE: 'edx.%prefix%.%domain%'
                EDXAPP_LMS_PREVIEW_NGINX_PORT: 80
                EDXAPP_CMS_NGINX_PORT: 80
                EDXAPP_LMS_NGINX_PORT: 80
                EDXAPP_PLATFORM_NAME: 'Rackspace Training (%prefix%)'
                
                EDXAPP_MYSQL_DB_NAME: 'edxapp'
                EDXAPP_MYSQL_USER: 'edxapp001'
                EDXAPP_MYSQL_PASSWORD: '%database_password%'
                EDXAPP_MYSQL_HOST: '%database_hostname%'
                EDXAPP_MYSQL_PORT: '3306'
                
                XQUEUE_MYSQL_DB_NAME: 'xqueue'
                XQUEUE_MYSQL_USER: 'xqueue001'
                XQUEUE_MYSQL_PASSWORD: '%database_password%'
                XQUEUE_MYSQL_HOST: '%database_hostname%'
                XQUEUE_MYSQL_PORT: '3306'
                
                ORA_MYSQL_DB_NAME: 'ora'
                ORA_MYSQL_USER: 'ora001'
                ORA_MYSQL_PASSWORD: '%database_password%'
                ORA_MYSQL_HOST: '%database_hostname%'
                ORA_MYSQL_PORT: '3306'
                
                COMMON_MYSQL_READ_ONLY_USER: 'read_only'
                COMMON_MYSQL_READ_ONLY_PASS: '%database_password%'
                COMMON_MYSQL_ADMIN_USER: 'admin'
                COMMON_MYSQL_ADMIN_PASS: '%database_password%'
                COMMON_MYSQL_MIGRATE_USER: 'migrate'
                COMMON_MYSQL_MIGRATE_PASS: '%database_password%'
                EOF
              params:
                "%database_hostname%": { get_attr: [ database, hostname ] }
                "%database_password%": { get_attr: [ password, value ] }
                "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
                "%domain%": { get_param: domain }
          - str_replace:
              template: |
                cat > /opt/cloud-training/runcmd-bash << EOF
                #!/bin/bash
                set -e
                set -x
                function exit_failure {
                  %swift_signal_notify% --data-binary '{"status": "FAILURE", "reason": "'"\$@"'"}'
                  exit 1
                }
                function exit_success {
                  %swift_signal_notify% --data-binary '{"status": "SUCCESS"}'
                }
                /usr/bin/pip install --upgrade pip || exit_failure "PIP Upgrade PIP Failure"
                /usr/local/bin/pip install --upgrade virtualenv || exit_failure "PIP Install Virtual Environment Failure"
                cd /var/tmp
                git clone -b release https://github.com/cloud-training/configuration.git || exit_failure "Git Clone Failure"
                cd /var/tmp/configuration
                git checkout cloud-training-birch || exit_failure "Git Checkout Failure"
                /usr/local/bin/pip install -r requirements.txt || exit_failure "PIP Install Requirements Failure"
                cd /var/tmp/configuration/playbooks
                ansible-playbook -c local ./edx_sandbox.yml -i "localhost," -e @/opt/cloud-training/ansible-environment.yml -vv || exit_failure "Ansible Playbook Run Failure"
                exit_success
                EOF
              params:
                "%swift_signal_notify%": { get_attr: [ swift_signal_handle_app1, curl_cli ] }
          - chmod 0700 /opt/cloud-training/runcmd-bash
          - /opt/cloud-training/runcmd-bash

  server_app1:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "%prefix%-edx-app1"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      flavor: 8 GB General Purpose v1
      image: Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - network: { get_resource: network }
      key_name: { get_resource: keypair }
      admin_pass: { get_attr: [ password, value ] }
      config_drive: True
      user_data_format: RAW
      user_data: { get_resource: cloud_config_app1 }

  dns:
    type: Rackspace::Cloud::DNS
    properties:
      name:
        str_replace:
          template: "%prefix%.%domain%"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
            "%domain%": { get_param: domain }
      emailAddress: ipadmin@stabletransit.com
      records:
        - type: A
          data: { get_attr: [ server_app1, accessIPv4 ] }
          name:
            str_replace:
              template: "edx.%prefix%.%domain%"
              params:
                "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
                "%domain%": { get_param: domain }
        - type: A
          data: { get_attr: [ server_app1, accessIPv4 ] }
          name:
            str_replace:
              template: "preview.edx.%prefix%.%domain%"
              params:
                "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
                "%domain%": { get_param: domain }
        - type: A
          data: { get_attr: [ server_app1, accessIPv4 ] }
          name:
            str_replace:
              template: "studio.edx.%prefix%.%domain%"
              params:
                "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
                "%domain%": { get_param: domain }

  swift_signal_app1:
    type: OS::Heat::SwiftSignal
    properties:
      handle: { get_resource: swift_signal_handle_app1 }
      count: 1
      timeout: 7200

outputs:
  password:
    description: Password
    value: { get_attr: [ password, value ] }
  private_key:
    description: Private Key
    value: { get_attr: [ keypair, private_key ] }
  url_lms:
    description: LMS URL
    value:
      str_replace:
        template: "http://edx.%prefix%.%domain%/"
        params:
          "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
          "%domain%": { get_param: domain }
  url_lms_preview:
    description: LMS (Preview) URL
    value:
      str_replace:
        template: "http://preview.edx.%prefix%.%domain%/"
        params:
          "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
          "%domain%": { get_param: domain }
  url_cms:
    description: CMS URL
    value:
      str_replace:
        template: "http://studio.edx.%prefix%.%domain%/"
        params:
          "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
          "%domain%": { get_param: domain }
