---
# This playbook deploys an edX (Birch) Environment

- name: Setup Mongo
  hosts: mongo[0]
  sudo: True
  gather_facts: True
  tasks:
    - name: Ping Hosts
      ping:

    - name: Install Required Packages
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - software-properties-common
        - python-software-properties
        - python-pip
        - python-apt
        - python-dev

    - name: PIP Install Required Packages
      pip: name={{ item }} state=present
      with_items:
        - pymongo

    - name: create a mongodb user
      mongo_user_1.8: database={{ item.database }} name={{ item.user }} password={{ item.password }} roles={{ item.roles }} replica_set=myreplset state=present
      with_items: MONGO_USERS

- name: Setup edX
  hosts: app
  sudo: True
  gather_facts: True
  tasks:
    - name: Ping Hosts
      ping:

    - name: PIP Install Required Packages
      pip: name={{ item }} state=latest
      with_items:
        - pip
        - virtualenv

    - name: Clone Repos
      git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.version }} force=yes
      with_items:
        - { repo: 'https://github.com/cloud-training/configuration.git',    dest: '/var/tmp/configuration',               version: 'cloud-training-birch'}
        - { repo: 'https://github.com/cloud-training/edx-heat-ansible.git', dest: '/opt/cloud-training/edx-heat-ansible', version: 'master'}

    - name: PIP Install Required Packages
      pip: requirements=requirements.txt state=present chdir=/var/tmp/configuration

- name: Install edX
  hosts: app
  sudo: True
  gather_facts: True
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/forum/defaults/main.yml
    - roles/ora/defaults/main.yml
    - roles/xqueue/defaults/main.yml
  roles:
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - ora
      - xqueue
      nginx_default_sites:
      - lms

- name: Install edX
  hosts: app[0]
  sudo: True
  gather_facts: True
  roles:
    - { role: 'edxapp', celery_worker: True, migrate_db: 'yes' }
    - { role: 'edxapp', migrate_db: 'yes' }
    - { role: 'xqueue', update_users: True, migrate_db: 'yes' }
    - { role: 'ora', migrate_db: 'yes', when: ENABLE_LEGACY_ORA }
    - demo

- name: Install edX
  hosts: app:!app[0]
  sudo: True
  gather_facts: True
  roles:
    - { role: 'edxapp', celery_worker: True, migrate_db: 'no' }
    - { role: 'edxapp', migrate_db: 'no' }
    - { role: 'xqueue', update_users: True, migrate_db: 'no' }
    - { role: 'ora', migrate_db: 'no', when: ENABLE_LEGACY_ORA }

- name: Install edX
  hosts: app
  sudo: True
  gather_facts: True
  serial: 1
  roles:
    - rabbitmq

- name: Install edX
  hosts: app
  sudo: True
  gather_facts: True
  roles:
    - oraclejdk
    - elasticsearch
    - forum
    - { role: 'notifier', NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - certs
    - edx_ansible
